project:
  type: website

website:
  title: "Ram√≥n"
  navbar:
    right:
      - text: "Blog"
        href: index.qmd
      - text: "Profile"
        href: about.qmd

format:
  html:
    theme: default
    css: styles.css
    mainfont: Inter
