project:
  type: website

website:
  title: "Ram√≥n"
  navbar:
    right:
      - text: "Blog"
        href: index.qmd
      - text: "Profile"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - style.scss
    mainfont: "EB Garamond, Georgia, serif"
    monofont: Fira Code, consolas, courier, monospace
    highlight-style: github
    include-in-header:
      text: |
        <style>
        @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap');
        </style>
